#!/bin/bash
set -e

# Run the build process
npm run buildminimal

echo "Finding generated build files..."

# Find the exact CSS and JS files generated by the build
HTML_FILE="dist/minimal.html"
CSS_FILE=$(find dist -type f -name "minimal.*.css")
JS_FILE=$(find dist -type f -name "minimal.*.js")

# Check if files were found
if [ -z "$CSS_FILE" ] || [ -z "$JS_FILE" ]; then
  echo "Error: Build files not found."
  exit 1
fi

echo "Renaming files..."
mv "$HTML_FILE" "dist/smoozoo.html"
mv "$CSS_FILE" "dist/smoozoo.css"
mv "$JS_FILE" "dist/smoozoo.js"

echo "Updating references in smoozoo.html..."

# Use the filenames we found earlier for the search/replace
sed -i \
  -e "s/$(basename "$CSS_FILE")/smoozoo.css/g" \
  -e "s/$(basename "$JS_FILE")/smoozoo.js/g" \
  "dist/smoozoo.html"

echo "Done."
